<?php

namespace My\schoolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * paiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paiementRepository extends EntityRepository
{
}
